/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/exercise-data`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/log-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/log-meal`; params?: Router.UnknownInputParams; } | { pathname: `/meal-data`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/select-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/select-meal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/survey`; params?: Router.UnknownInputParams; } | { pathname: `/view-photo`; params?: Router.UnknownInputParams; } | { pathname: `/log-meal-manual`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calorie-tracking` | `/calorie-tracking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercise-tracking` | `/exercise-tracking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/water-tracking` | `/water-tracking`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/exercise-data`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/log-exercise`; params?: Router.UnknownOutputParams; } | { pathname: `/log-meal`; params?: Router.UnknownOutputParams; } | { pathname: `/meal-data`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/select-exercise`; params?: Router.UnknownOutputParams; } | { pathname: `/select-meal`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/survey`; params?: Router.UnknownOutputParams; } | { pathname: `/view-photo`; params?: Router.UnknownOutputParams; } | { pathname: `/log-meal-manual`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calorie-tracking` | `/calorie-tracking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exercise-tracking` | `/exercise-tracking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/water-tracking` | `/water-tracking`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/exercise-data${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/loading${`?${string}` | `#${string}` | ''}` | `/log-exercise${`?${string}` | `#${string}` | ''}` | `/log-meal${`?${string}` | `#${string}` | ''}` | `/meal-data${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/select-exercise${`?${string}` | `#${string}` | ''}` | `/select-meal${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/survey${`?${string}` | `#${string}` | ''}` | `/view-photo${`?${string}` | `#${string}` | ''}` | `/log-meal-manual${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calorie-tracking${`?${string}` | `#${string}` | ''}` | `/calorie-tracking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exercise-tracking${`?${string}` | `#${string}` | ''}` | `/exercise-tracking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/water-tracking${`?${string}` | `#${string}` | ''}` | `/water-tracking${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/exercise-data`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/log-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/log-meal`; params?: Router.UnknownInputParams; } | { pathname: `/meal-data`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/select-exercise`; params?: Router.UnknownInputParams; } | { pathname: `/select-meal`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/survey`; params?: Router.UnknownInputParams; } | { pathname: `/view-photo`; params?: Router.UnknownInputParams; } | { pathname: `/log-meal-manual`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calorie-tracking` | `/calorie-tracking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercise-tracking` | `/exercise-tracking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/water-tracking` | `/water-tracking`; params?: Router.UnknownInputParams; };
    }
  }
}
